NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/identity-jwclab-com-32769.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/identity-jwclab-com-32769.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/identity-jwclab-com-32769.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/identity-jwclab-com-32769.pem
    OrganizationalUnitIdentifier: orderer
